= Agregar un nuevo estándar

WARNING: Esta página contiene instrucciones de configuración solo para usuarios avanzados de IPT 

El IPT siempre se instala con 3 cores del estándar Darwin Core cargados de forma predeterminada: "taxon", "occurrence" y "event". Desde la versión 2.1 de IPT, existe la posibilidad de agregar cores personalizados, lo que es útil para las comunidades que crean prototipos de nuevos estándares de datos. De esta manera, su comunidad puede comenzar a intentar mapear sus datos al nuevo estándar y refinar iterativamente su conjunto de propiedades.

Los 3 pasos siguientes explican cómo hacerlo

. crear su nuevo core,
. registrarlo en GBIF, y
. configurar un IPT para utilizarlo.

== Instrucciones

. *Escribir la definición del core XML*
+
The core XML definition has to comply with the http://rs.gbif.org/schema/extension.xsd[GBIF Extension Schema]. It is easiest to simply adapt an existing core definition, such as the {latest-dwc-occurrence}[Darwin Core Occurrence Core]. Please note, the core definition must contain a property that serves as the record identifier (e.g. http://rs.tdwg.org/dwc/terms/occurrenceID for the Occurrence core, or http://rs.tdwg.org/dwc/terms/eventID for the Event Core. The process of creating a new non-core extension is exactly the same as for a core extension. The process of creating a new vocabulary (as a data type for a property within the core, or non-core extension) is different only in that the XML definition has to comply with the http://rs.gbif.org/schema/thesaurus.xsd[GBIF Thesaurus Schema]. Once again, it is easiest to adapt an existing vocabulary definition, such as the {latest-basis-of-record}[Darwin Core Type vocabulary].

. *Registrar el core con GBIF*
+
Si bien la definición del core aún está experimentando cambios, se registra en GBIF Sandbox Registry. Para registrar su core, realice una solicitud de extracción al repositorio rs.gbif.org siguiendo https://github.com/gbif/rs.gbif.org/blob/master/versioning.md#how-to-create-a-new-version-of-an-extension-or-vocabulary-on-rsgbiforg[estas instrucciones]. Si pasa la inspección, se fusionará con https://rs.gbif.org/sandbox/core/ y se incluirá en la https://gbrdsdev.gbif.org/registry/extensions.json[Lista de Sandbox Registry de extensiones]. Cuando se haya finalizado la definición principal, lo que significa que su conjunto de propiedades se ha congelado, se alojará en https://rs.gbif.org/core/ y se incluirá en https://gbrds.gbif.org/registry/extensions.json[Lista de extensiones de Live Registry]. El mismo proceso se aplica al registro de extensiones y vocabularios secundarios.

. *Configurar el IPT*
+
--
Para configurar el IPT para usar el {sandbox-material-sample}[Material de ejemplo del core], por ejemplo, agregue las siguientes 2 líneas a `$IPT_DATA_DIR/config/ipt.properties`.

NOTE: asegúrese de evitar los dos puntos como en el caso anterior*

----
ipt.core_rowTypes=http\://rs.tdwg.org/dwc/terms/MaterialSample
ipt.core_idTerms=http\://rs.tdwg.org/dwc/terms/materialSampleID
----

Esto configura el IPT para reconocer todas las extensiones con rowType http://rs.tdwg.org/dwc/terms/MaterialSample como core principales y para usar http://rs.tdwg.org/dwc/terms/materialSampleID como su término identificador. Se pueden especificar varios núcleos, delimitándolos con el carácter de barra vertical `|` (pipe). La primera entrada de ipt.core_idTerms es el ID de la primera entrada de core_rowTypes y así sucesivamente. Por último, guarde el archivo ipt.properties, reinicie Tomcat y luego xref:Administration.adoc#install-extension[instale el core]. El core ahora está disponible para su uso en el IPT.
--
